### ISSUE TITLE
linebreaks invisible

### ISSUE THREAD

**Issue by ch-sander** [scta-texts/p9i7y5#2]
It seems many of the ¬ are gone to mark works extending over two lines.

**Comment by jeffreycwitt** [comment]
these have been replaced with <lb break="no"/>, so the data is retained and can be easily visualized ¬

Is it important distinguish between broken words that contain ¬ and broken words that do not? 

I tend to not think it since ¬ is basically a symbol to tell us that the words go together.

**Comment by ch-sander** [comment]
Don't I get it?

How do we see that there's a line break within the word?

![grafik](https://user-images.githubusercontent.com/74921235/159796574-a68e100e-b398-49be-bea4-62452dc50291.png)
