### ISSUE TITLE
image regions

### ISSUE THREAD

**Issue by ch-sander** [scta-texts/p9i7y5#7]
adjust:
https://scta.lombardpress.org/text?resourceid=http://scta.info/resource/p9i7y5-de5065-Fd1e272
https://scta.lombardpress.org/text?resourceid=http://scta.info/resource/p9i7y5-e14827-Fd1e547
https://scta.lombardpress.org/text?resourceid=http://scta.info/resource/p9i7y5-e28534-Fd1e193
https://scta.lombardpress.org/text?resourceid=http://scta.info/resource/p9i7y5-e36231-Fd1e728
https://scta.lombardpress.org/text?resourceid=http://scta.info/resource/p9i7y5-e36231-Fd1e781
https://scta.lombardpress.org/text?resourceid=http://scta.info/resource/p9i7y5-e22834-Fd1e186

**Comment by ch-sander** [comment]
If I understood correcty, this can be fixed by simply copying the coordinated from the manifestation (which appear to be correct) to the coordinates for the figure expression that serve the search thumbnail view.

**Comment by jeffreycwitt** [comment]
Yes, thanks for this list. I'll work on it.

**Comment by jeffreycwitt** [comment]
I think this is resolved now
